---
name: Merge to Main
on:
  push:
    branches:
    - main
jobs: 
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          registry-url: https://npm.pkg.github.com/
          scope: '@stephanieea'
      - run: npm ci

      - name: Update and Publish Canary Version
        id: update-publish-canary
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version prerelease
          git push
          npm publish --tag canary --access public
...