---
name: Release
on:
  release:
    types: [created]
      
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    if: github.ref_type == 'tag'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          registry-url: https://npm.pkg.github.com/
          scope: '@stephanieea'
      - run: npm ci
      - name: Pubish Patch
        id: publish-patch
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          npm version patch --no-git-tag-version
          npm publish --access public
...